swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Simios"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "ingridmazoni@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "simios.swagger.io"
basePath: "/simios"
tags:
- name: "Simian"
  description: "Everything about Simian"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"

schemes:
- "https"
- "http"
paths:
  /simian:
    post:
      tags:
      - "Simian"
      summary: "Detects Valid DNA Sequence"
      description: ""
      operationId: "isSimian"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "dna"
        description: ""
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/Dna'
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "HTTP 403-FORBIDDEN"
              
      
   
  /stats:
    get:
      tags:
      - "Simian"
      summary: "Population statistics of Simios and Humans"
      description: ""
      operationId: "stats"
      produces:
      - "application/json"
      
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Stats"
          
        "403":
          description: "HTTP 403-FORBIDDEN"        
      
definitions:
  Stats:
    type: "object"
    properties:
      count_mutant_dna:
        type: "number"
        format: "double"
      count_human_dna:
        type: "integer"
        format: "int32"
      ratio:
        type: "integer"
        format: "int32"  
      
  Dna:
    type: "object"
    properties:
      dna:
        type: "string"
      
  
 
