swagger: "2.0"
info:
  description: "API para verificação de DNA dos Simios"
  version: "1.0.0"
  title: "Simios"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "ingridmazoni@outlook.com"
    name: "Ingrid Mazoni"
    url: "http://www.ingridmazoni.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/simios"
tags:
- name: "Simios"
  description: "Tudo sobre simios"
  externalDocs:
    description: "leia mais sobre na documentação"
    url: "localhost:8080/v2/api-docs"

schemes:
- "https"
- "http"
paths:
  simian:
    post:
      tags:
      - "Simios"
      summary: "Detects Valid DNA Sequence"
      description: ""
      operationId: "isSimian"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "dna"
        description: "sequencia de dna"
        required: true
        schema:
          $ref: '#/definitions/Dna'
           
      responses:
        "200":
          description: "successful operation"
          schema:
              $ref: "#/definitions/ResponseSimian"  
        "403":
          description: "HTTP 403-FORBIDDEN"
              
      
   
  stats:
    get:
      tags:
      - "Simios"
      summary: "Population statistics of Simios and Humans"
      description: ""
      operationId: "stats"
      produces:
      - "application/json"
      
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Stats"
          
        "403":
          description: "HTTP 403-FORBIDDEN"        
      
definitions:
  Stats:
    type: "object"
    properties:
      count_mutant_dna:
        type: "integer"
        format: "int64"       
      count_human_dna:
        type: "integer"
        format: "int64"
      ratio:
        type: "number"
        
  Dna:
    type: object
    properties:
      dna:
        type: array
        items:
          type: string
      
  ResponseSimian:
    type: "object"
    properties:
      isSimian:
        type: "boolean"
      sequenciaDna:
         $ref: "#/definitions/Dna"
      

externalDocs:
  description: "Tudo sobre Simios"
  url: "localhost:8080/swagger-ui.html"  
    
      
         
      
  
 
